### ISSUE TITLE
Question: Way To Save Map Markers?

### ISSUE THREAD

**Issue by Vegas-zzz** [code34/inidbi2#3]
Is there a way to write map markers to the database with inidbi2?

**Comment by code34** [comment]
inidbi2 is a low level file reader/writer, you can write with it what you want. It doesn't manage functionnal view.

If you want to save a marker or anything else, you have to save all informations concerning the marker, to restore it create a new marker and use thoses informations.

**Comment by Vegas-zzz** [comment]
Any tips on how to accomplish this? I think having a legitimate option for saving markers in Arma 3 would be very popular!

**Comment by code34** [comment]
look into oo_pdw code you should find some good ideas about how to do this :)
