### ISSUE TITLE
Read Command that returns the "Key"

### ISSUE THREAD

**Issue by CommandoKain** [code34/inidbi2#5]
Trying to get the Value Name of the "Key". The read command only wants to give me the value of what is stored in "Key".
_loadout = ["read",["Rifleman Class","AKM"]] call _inidbi;  // returns the list of gear stored in AKM

However...

_loadouts = ["read",["Rifleman Class"]] call _inidbi; // Does not return "AKM"

Would like a command that will give me that ablility to
grab AKM then use that to get the list of gear from it.

In my GUI script im trying to add the ablity for players to Name there loadouts 
so the Key value could be and thing. in this case I named it it AKM.

This is from my InitServer.sqf
"LoadoutsaveData" addPublicVariableEventHandler
{
	private ["_data"];
	_data = (_this select 1);
	_UID = (_data select 0);
	_RifleLoadout = (_data select 1);
	_LoadOutName = (_data select 2);
	
	_inidbi = ["new",_UID] call OO_INIDBI;
	
	["write", ["Rifleman Class",_LoadOutName,_RifleLoadout]] call _inidbi;
};

Database as follows:
[Player Info]
Name=""COMMANDO_KAIN""
UID=""XXXXXXXXXXXX""
[Player XP]
XP="0"
[Rifleman Class]
AKM="[["arifle_AKM_F","","","",["30Rnd_762x39_Mag_F",30],[],""],[],[],["U_B_CombatUniform_mcam",[["30Rnd_762x39_Mag_F",3,30]]],[],["B_AssaultPack_rgr",[["30Rnd_762x39_Mag_F",1,30]]],"H_HelmetSpecB_sand","G_Balaclava_TI_blk_F",[],["","","","","",""]]"

**Comment by code34** [comment]
Hi,

The best and simple way to do what you want to do is to add a loadoutname key and give it the value return by the player "akm".

**Comment by code34** [comment]
note: Im checking from my part an improvement about this too

**Comment by code34** [comment]
"getKeys" method was added to 2.06 release

**Comment by y0014984** [comment]
This new method is very helpful. Thank you.
