### ISSUE TITLE
publish 2.06 to steam workshop

### ISSUE THREAD

**Issue by y0014984** [code34/inidbi2#7]
Hi, please publish INIDBI2 2.06 to steam workshop.  #There is no official release but only a re-upload from another guy with version 2.05.

I would like to reference the official version in my mod dependancies. Thank you.

**Comment by code34** [comment]
hi

done :)

https://steamcommunity.com/sharedfiles/filedetails/?id=1768992669

**Comment by y0014984** [comment]
Cool. Thank you.
