### ISSUE TITLE
Possible error with |

### ISSUE THREAD

**Issue by Tress16** [code34/inidbi2#8]
It is possible that there is an error when saving if a | occurs in the word?
In my case i'm trying to save the username **The | Day...**.

The result is: **Name=""The**
Should be: **Name=""The | Day...""**

Errorlog from RTP:
```
21:37:51 Error in expression <[true,""The]>
21:37:51   Error position: <The]>
21:37:51   Error Missing ]
21:37:51 Error in expression <[true,""The]>
21:37:51   Error position: <The]>
21:37:51   Error Missing ]
21:37:51 Error in expression <y];
_result = call compile _result;

if(_result select 0) then {
_data = _result>
21:37:51   Error position: <_result select 0) then {
_data = _result>
21:37:51   Error Undefined variable in expression: _result
21:37:51 File \inidbi2\oo_inidbi.sqf [BIS_fnc_inidbi2]..., line 496
```

**Comment by code34** [comment]
you have to use this method before to change the default field delimiter: 
["setSeparator", _separator] call _inidbi;

**Comment by Tress16** [comment]
1. Can I use it in a db that still exist?
2. Do I have to change the separators everywhere (get ... / set ...)?

Sorry, have no experience with that.


Will try this:
```
params ["_caller", "_nameDB", "_playerName", "_hint"];
private _inidbi = ["new", _nameDB] call OO_INIDBI;
private _separator = "s|";
["setSeparator", _separator] call _inidbi;    // will set separator as "|s|"
private _fileExist = "exists" call _inidbi;
```

**Comment by code34** [comment]
1.yes. If you are afraid about data, you can also backup your ini file
2. correct. after each instanciation: private _inidbi = ["new", _nameDB] call OO_INIDBI;
3. correct. you have to check if you have no "|s|" caracters in your text, that you use for your own usage.

**Comment by Tress16** [comment]
Now I'm having problems with loading my profile.
It happends only if I restart the server and joining as the first client.
I'm using the newest version (2.06).


```
params ["_caller", "_nameDB", "_playerName", "_hint"];
private _inidbi = ["new", _nameDB] call OO_INIDBI;
private _separator = "s|";
["setSeparator", _separator] call _inidbi;    // will set separator as "|s|"
private _fileExist = "exists" call _inidbi;
private _text = "WELCOME - NEW PROFILE CREATED";
sleep 3;



// CHECK IF DB EXIST
if (_fileExist) then { ... } else { ... };
```

**Comment by code34** [comment]
If you need assistance about how to use INDBI, you can use the forum:
https://forums.bohemia.net/forums/topic/186131-inidbi2-save-and-load-data-to-the-server-or-your-local-computer-without-databases/?page=13&tab=comments#comment-3398311

This issue tracker is only to report bug relative to inidbi code.
