### ISSUE TITLE
Write data limited to 8000 - How to increase 

### ISSUE THREAD

**Issue by prayerz** [code34/inidbi2#9]
Hello Code34,

I'm currently using your awesome Inidbi2 mod to save datas for a persistent campaign.
I'm saving Vehicle HitPointsDamage in a section that easily goes above 8000 char.

Is there a way to increase the 8K limitation within the dlls ?

Thanks for your help and for your great mod !

Prayerz

**Comment by code34** [comment]
Hello Prayez

This limitation came from callextension command. I don't know if they change it now.

There is several way to extend it:
- the simple one is to change the hardcoded value in the different function of the dll and sqf interface
- the other way is to change the dll to stream some chunk of datas to the sqf interface, and recompose them

**Comment by prayerz** [comment]
Hey Code34,

Thanks for you Quick answer !
Any way you could do change the hardcoded value ?

I've found the value in the sqf file but I can't update the dll's one as I dont have visual studio.

If you could the update and send me the updated files it would be so awesome. 

Thanks again for your help

**Comment by code34** [comment]
Sorry, there is no support regarding this tool other than tips for modifying it.

My goal is not to do for others but to teach others to do :)

**Comment by prayerz** [comment]
Code34, 

No problem with that ! 
So I managed to install VS 2015, I loaded your inidbi2 project which made me install the .Net Framework 4.7.2. Without changing anything, i wanted to build back the dlls.
When i'm trying to build using the 4.7.2 (x64 or x84) i got error messages : 

```
The "DllExportAppDomainIsolatedTask" task failed unexpectedly.
System.ArgumentException: Requested value 'Version47' was not found.
```

If i build with .Net Framework 4.5 there is no error and the dlls are generated. But, i got error message when launching the mod (saying my version of inidbi2 mod would only run on 32-Bit). And persistence doesn't seem to work.

Could you help me on setting up my VS, or the building part ?

Thanks again !

**Comment by prayerz** [comment]
Hey Code34,

I was finally able to build the dlls with VS 2017.
Will look on how to increase data send with callExtension and will tell you if i make it work.

Thanks again.
